import sys
import csv

if sys.version_info <= (3,0,0):
	print('Python version 3.0 or higher required.')
else:    
	print('Creating XML file...')
	reader = csv.reader(open('27fb8bcc-23cb-4e85-b5b4-fde68a8ef93a.csv', 'r', encoding='utf-8').readlines()[1:], delimiter=',')
	f = open('27fb8bcc-23cb-4e85-b5b4-fde68a8ef93a.xml', 'w', encoding='utf-8')
	f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
	f.write('<!DOCTYPE RDF>\n')
	f.write('<rdf:RDF\n')
	f.write('xmlns:owl="http://www.w3.org/2002/07/owl#"\n')
	f.write('xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"\n')
	f.write('xmlns:xsd="http://www.w3.org/TR/xmlschema11-1#"\n')
	f.write('xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n')
	f.write('xmlns:gn="http://www.geonames.org/ontology#"\n')
	f.write('xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"\n')
	f.write('xmlns:dct="http://purl.org/dc/terms/"\n')
	f.write('xmlns:gml="http://www.opengis.net/gml/3.2"\n')
	f.write('xmlns:gmd="http://www.isotc211.org/2005/gmd"\n')
	f.write('xmlns:on="http://opennorth.se/voc/">\n')
	for row in reader:
		f.write('	'+'<!-- Internal id number -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#Id">\n')
		f.write('		'+'<rdfs:label>Id</rdfs:label>\n')
		f.write('		'+'<xsd:integer>'+row[0]+'</xsd:integer>\n')
		f.write('		'+'<xml:lang>se</xml:lang>\n')
		f.write('		'+'<xsd:literal>Unik identifierare</xsd:literal>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- Country Code -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#CountryCode">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Country Code</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Landkod</rdfs:label>\n')
		f.write('		'+'<gn:countryCode>'+row[1]+'</gn:countryCode>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- Municipality Code -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#MunicipalityCode">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Municipality Code</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Kommunkod</rdfs:label>\n')
		f.write('		'+'<xsd:integer>'+row[2]+'</xsd:integer>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- IVL number -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#IVLnumber">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Measurement Station IVL-number</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Mätstationens IVL-nummer</rdfs:label>\n')
		f.write('		'+'<xsd:integer>'+row[3]+'</xsd:integer>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- Geocode -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#Geocode">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Geo code for the location of the measurement station</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Mätstationens geoposition</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">kartografiskt referenssystem</rdfs:label>\n')
		f.write('		'+'<gml:name>SWEREF99 20 15 + RH2000 height</gml:name>\n')
		f.write('		'+'<geo:Point>\n')
		f.write('			'+'<xsd:float><geo:long>'+row[4].split(', ')[0]+'</geo:long><geo:lat>'+row[4].split(', ')[1]+'</geo:lat></xsd:float>\n')
		f.write('		'+'</geo:Point>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- Designation -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#Designation">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Designation of Measurement Station</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Mätstationens benämning</rdfs:label>\n')
		f.write('		'+'<xsd:literal>'+row[5]+'</xsd:literal>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- Time of Measurement -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#TimeOfMeasuretime">\n')
		f.write('		'+'<rdfs:label xml:lang="se">Mättidpunkt</rdfs:label>\n')
		f.write('		'+'<xsd:dateTime>'+row[6]+'</xsd:dateTime>\n')
		f.write('		'+'<rdfs:isDefinedBy rdf:resource="http://dbpedia.org/page/Timestamp"/>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- Time zone -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#TimeZone">\n')
		f.write('		'+'<rdfs:label xml:lang="se">Tidzon</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="en">Timezone</rdfs:label>\n')
		f.write('		'+'<xsd:literal>'+row[7]+'</xsd:literal>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- NO2 -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#NO2">\n')
		f.write('		'+'<rdfs:label>NO2</rdfs:label>\n')
		f.write('		'+'<xsd:integer>'+row[8]+'</xsd:integer>\n')
		f.write('		'+'<rdfs:isDefinedBy rdf:resource="http://dbpedia.org/page/NOx"/>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- NO2-unit -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#NOxUnit">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Unit NO2</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Enhet NO2</rdfs:label>\n')
		f.write('		'+'<xsd:literal>'+row[9]+'</xsd:literal>\n')
		f.write('		'+'<rdfs:isDefinedBy xsd:literal="Enheten som används för det mätvarde som anges för för NO2"/>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- PM10 -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#PM10">\n')
		f.write('		'+'<rdfs:label>PM10</rdfs:label>\n')
		f.write('		'+'<xsd:integer>'+row[10]+'</xsd:integer>\n')
		f.write('		'+'<rdfs:isDefinedBy rdf:resource="http://dbpedia.org/page/Particulates"/>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- PM10-unit -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#PM10Unit">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Unit PM10</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Enhet PM10</rdfs:label>\n')
		f.write('		'+'<xsd:literal>'+row[11]+'</xsd:literal>\n')
		f.write('		'+'<rdfs:isDefinedBy xsd:literal="Enheten som används för det mätvarde som anges för för PM10"/>\n')
		f.write('	'+'</rdf:Description>\n')
		f.write('	'+'<!-- Alarm Type -->\n')
		f.write('	'+'<rdf:Description rdf:about="http://opennorth.se/voc#AlarmType">\n')
		f.write('		'+'<rdfs:label xml:lang="en">Alarm Type</rdfs:label>\n')
		f.write('		'+'<rdfs:label xml:lang="se">Larmtyp</rdfs:label>\n')
		f.write('		'+'<xsd:integer>'+row[12]+'</xsd:integer>\n')
		f.write('	'+'</rdf:Description>\n')		
	f.write('</rdf:RDF>')
	f.close()
	print('XML file created!')
